### ISSUE TITLE
Example 06_AutomationDiagram crashes on startup

### ISSUE THREAD

**Issue by bobkr** [afrl-rq/OpenUxAS#9]
With a new build Aug 18, 2020 the 06 example produces the following trace:

 
(vpython) bob@bob-MacBookPro:~/bootstrap$ ./run-example 06_AutomationDiagram 
Using run-example in /home/bob/bootstrap/sbx/x86_64-linux/uxas-release/src.
 
<>RoutePlannerVisibility::Vehicle Id [3] turnRadius_m[135.6] nominalMaxBankAngle (deg) [20] nominalSpeed_mps[22]
<>RoutePlannerVisibility::Vehicle Id [4] turnRadius_m[135.6] nominalMaxBankAngle (deg) [20] nominalSpeed_mps[22]
<>RoutePlannerVisibility::Vehicle Id [5] turnRadius_m[135.6] nominalMaxBankAngle (deg) [20] nominalSpeed_mps[22]
<>RoutePlannerVisibility::Vehicle Id [6] turnRadius_m[135.6] nominalMaxBankAngle (deg) [20] nominalSpeed_mps[22]
Aug 18, 2020 3:12:22 PM avtas.lmcp.LMCPXMLReader setValue
SEVERE: null
java.lang.NumberFormatException: For input string: ""
at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:68)
at java.base/java.lang.Long.parseLong(Long.java:709)
at java.base/java.lang.Long.parseLong(Long.java:824)
at avtas.lmcp.LMCPXMLReader.readPrimitive(LMCPXMLReader.java:204)
at avtas.lmcp.LMCPXMLReader.setValue(LMCPXMLReader.java:145)
at avtas.lmcp.LMCPXMLReader.readXML(LMCPXMLReader.java:73)
at avtas.amase.scenario.MessageManager.getNextEvent(MessageManager.java:104)
at avtas.amase.scenario.ScenarioManager.step(ScenarioManager.java:148)
at avtas.amase.scenario.ScenarioManager.initScenario(ScenarioManager.java:104)
at avtas.amase.scenario.ScenarioManager.initializeComplete(ScenarioManager.java:225)
at avtas.app.Context.initialize(Context.java:363)
at avtas.app.Application.createApplication(Application.java:120)
at avtas.app.Application.createApplication(Application.java:82)
at avtas.app.Application$3.run(Application.java:247)
at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
 
1597788745961 WARN:  - automation request ID[91] was not ready in time and was not sent.

**Comment by lhumphrey** [comment]
Thanks for catching this. I was able to duplicate the issue on my machine. I suspect I know what the issue is, and I'll work on a fix.

**Comment by lhumphrey** [comment]
I've pushed an update to this example that should fix the issue.

**Comment by bobkr** [comment]
Thanks, Just re-tested it and it works.

**Comment by lhumphrey** [comment]
Great! Glad it works now!
